#!/bin/bash

set -e


tea +charm.sh/gum gum format --<<EOMD
# setup a git hook for prepare-commit-msg

## what to expect from this script

* checks for \`.git\` repository
* fetches "prepare-commit-msg" script from remote 
* adds "prepare-commit-msg" in git hooks dir
* adds \`OPENAI_API_KEY\` to env
EOMD

tea +charm.sh/gum gum confirm "shall we continue?"


if ! test -d ".git";
# if no .git dir found, then ask to go to a git directory
then
  echo "no git directory found" >&2
  exit 1
fi

# clone prepare-commit-msg file to git_hook_path
GIT_HOOKS_PATH=$(tea +git-scm.org git rev-parse --git-path hooks)
tea +gnu.org/wget wget -O $GIT_HOOKS_PATH/prepare-commit-msg https://gist.githubusercontent.com/stoooops/d9a633626c0b429146f3a7c4ad224716/raw/07367236e0dc3951a78b518866a2c4fea075ea4c/prepare-commit-msg.py

chmod +x $GIT_HOOKS_PATH/prepare-commit-msg

# unset git core.editor locally
tea +git-scm.org git config --local --unset core.editor


# add OPENAI_API_KEY to env
tea +charm.sh/gum gum format "finally, you need an \`OPENAI\` API key in your environment"
OPENAI_API_KEY=$(gum input --prompt "what your \`OPENAI_API_KEY\`? ")

export OPENAI_API_KEY=$OPENAI_API_KEY

tea +charm.sh/gum gum format <<EOMD
# done!
Your git commits will now be generated by AI! 
EOMD
